[workspace]
members = [
    "src/cli",
    "src/codegen",
    "src/core",
    "src/macros",
    "src/toasty",

    # Driver implementations
    "src/db/ddb",
    "src/db/sqlite",

    # General utilities.
    "src/std-util",

    # Examples
    "toasty-examples",

    # Tests
    "tests/client",
]

resolver = "2"

